### ISSUE TITLE
All method calls need to accept the extra args

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#11]
All LVM's commands accept extra arguments (like `-vvvv` or `--config=`) so to provide the same functionality, all the DBus API's methods need to accept the extra arguments too. Even methods like `PV.ReSize()` and `PV.Remove()` that take one and zero arguments, respectively. E.g. `--config="log{level=7}"`could be used to request debugging output to go to syslog which might be useful for all commands/actions.

**Comment by tasleson** [comment]
@vpodzime Yes, this is a good idea.  Additionally I was thinking that we could have methods on the Manager interface that would allow the user to set some of these changes up globally for their session.  So that they don't have to pass it on every call.  Only issue is if a user makes a change that changes the output it could break the parser, especially the --config.

**Comment by vpodzime** [comment]
The parser may need some improvements so that it skips lines that don't look like something it should process. And the first step might be to use different output format. Compare e.g. the output of `lvs` and `lvs --noheadings --nameprefixes --nosuffix --units=b`.

**Comment by tasleson** [comment]
All methods have `options` with commit 9c825dfb769131e165ad949fff84c2a4c41142a4.  Parser improvements will come later when we convert to JSON.

**Comment by vpodzime** [comment]
Very nice, thanks @tasleson!
