### ISSUE TITLE
No properties visible on Thinpool objects

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#40]
If I run 'd-feet' and go to some `Thinpool` object I don't see any properties defined for it. And the `Get()` method on the `...Properties` interface reports and error.

**Comment by tasleson** [comment]
When I added the Lv.Activate/Deactivate and TagsAdd/TagsDel I incorrectly hard coded the interface to `com.redhat.lvmdbus1.Lv` see fix (8a03ec013a5e0a002f0a73e1d32a63da509b2e09) .  This caused the `ThinPool` objects to have two interfaces `Lv` and `ThinPool`.   The properties did exist, they were on the `ThinPool` interface, not the `Lv` interface.   With the correction there is only the `ThinPool` interface.

I ran some interactive tests with the `Properties` interface and things appear to be working.  Please attach the error message.  Please note that when you call `Get` or `GetAll` you do need to specify argument(s) (`interface` for `GetAll`, `interface, property_name` for `Get`.  Otherwise you get a nice cryptic error like:

`g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):\n  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 826, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\nTypeError: GetAll() takes exactly 2 arguments (1 given)\n (36)'`

Thanks!

**Comment by vpodzime** [comment]
If I use the `"com.redhat.lvmdbus1.ThinPool"` interface, I get the properties. But d-feet isn't using showing that interface for the object at all:
![d-feet_thpool_props](https://cloud.githubusercontent.com/assets/1044278/11715073/3ed60fb6-9f3f-11e5-8553-60fb16941fc8.png)

The `"com.redhat.lvmdbus1.Lv"` interface doesn't work for the properties. I think the way this should be implemented is to provide the common stuff (methods and properties) in the `"com.redhat.lvmdbus1.Lv"` interface and the thin-pool-specific stuff in the `"com.redhat.lvmdbus1.ThinPool"` interface.

**Comment by tasleson** [comment]
This is odd, on my setup for a thin pool I don't get the Lv interface at all:
![thinpool](https://cloud.githubusercontent.com/assets/2520480/11724389/687e4bfe-9f39-11e5-82bf-2c081215823c.png)

Originally I had made it so that a thin pool has both the Lv and ThinPool interfaces where the ThinPool only offered the LvCreate method.

**Comment by tasleson** [comment]
@vpodzime OK, I was able to reproduce this once I had both thinpool LVs and regular LVs.  At the moment I don't understand why, but the dbus library is generating introspection data for the ThinPool as it is for a Lv.  Basically the metadata is incorrect, but if you try to retrieve the properties etc. they do work.  As you are wanting multiple interfaces for a single object I'm working on that change and then verifying that the introspection data is indeed correct.

**Comment by tasleson** [comment]
OK, hopefully this issue is now addressed with commit 5f1e8c726a9f1fed39ae0d37eafb37097bdcc0b6.  The service now exports both a Lv and ThinPool interface for the ThinPool objects.

**Comment by vpodzime** [comment]
It of course does, thanks!
