### ISSUE TITLE
Vg.Rename() doesn't update the database of objects

### ISSUE THREAD

**Issue by vpodzime** [tasleson/lvm-dubstep#60]
When I use the `Rename()` method on a Vg and then use the new name in `LookUpByLvmId()`, I get "/' as if the Vg didn't exist. The old name works. So clearly the database/dictionary of objects is not updated with the new name after the VG rename.

**Comment by tasleson** [comment]
@vpodzime Very good catch!  Unfortunately this specific fix is easy, but I discovered a bigger issue with re-naming the VG.  All the LVs on the VG fail to look-up correctly too.  This issue is a little more involved, especially when we add hidden LVs into the mix as well.  Working on a fix that addresses all these look-up failures.

**Comment by tasleson** [comment]
Addressed with 9823497487016fd16aa6f674699820824823ff73

**Comment by vpodzime** [comment]
Amazing, thanks!
